import { describe, expect, it } from "vitest";
import entry from "./index.js";
import { getToolPluginMetadata } from "openclaw/plugin-sdk/tool-plugin";

describe("dorothy-control", () => {
  it("declares tool metadata", () => {
    expect(getToolPluginMetadata(entry)?.tools.map((tool) => tool.name)).toEqual([
      "dorothy_health",
      "dorothy_memory_search",
      "dorothy_memory_list",
      "dorothy_memory_remember",
      "dorothy_memory_forget",
      "dorothy_mac_status",
      "dorothy_power_schedule",
      "dorothy_power_control",
      "dorothy_applications",
      "dorothy_application_control",
      "dorothy_note",
      "dorothy_create_reminder",
      "dorothy_capture_communication_task",
      "dorothy_restart_service",
      "dorothy_news",
      "dorothy_elorus_receivables",
      "dorothy_elorus_invoices",
      "dorothy_elorus_estimates",
      "dorothy_elorus_payments",
      "dorothy_finance_pnl",
      "dorothy_finance_profitability",
      "dorothy_finance_renewals",
      "dorothy_banking_summary",
      "dorothy_apple_note_create",
      "dorothy_apple_notes_search",
      "dorothy_calendar_upcoming",
      "dorothy_personal_dates",
      "dorothy_file_search",
      "dorothy_file_open",
      "dorothy_mail_accounts",
      "dorothy_mail_inbox",
      "dorothy_mail_needs_reply",
      "dorothy_mail_message",
      "dorothy_mail_financial_deadlines",
      "dorothy_mail_mark_read",
      "dorothy_imessage_recent",
      "dorothy_imessage_conversations",
      "dorothy_imessage_needs_reply",
      "dorothy_imessage_send",
      "dorothy_mail_reply",
      "dorothy_mail_compose",
      "dorothy_communications_summary",
      "dorothy_messenger_recent",
      "dorothy_messenger_needs_reply",
      "dorothy_instagram_recent",
      "dorothy_instagram_needs_reply",
      "dorothy_viber_recent",
      "dorothy_viber_needs_reply",
      "dorothy_viber_contact_messages",
      "dorothy_browser_open_url",
      "dorothy_browser_new_tab",
      "dorothy_browser_list_tabs",
      "dorothy_browser_find_tab",
      "dorothy_browser_play_media",
      "dorothy_browser_play_youtube_likes",
      "dorothy_browser_switch_tab",
      "dorothy_browser_read_page",
      "dorothy_browser_extract_visible_text",
      "dorothy_browser_read_message_thread",
      "dorothy_browser_screenshot",
      "dorothy_browser_click_text",
      "dorothy_browser_fill_field",
      "dorothy_browser_press_key",
      "dorothy_browser_scroll",
      "dorothy_browser_download_file",
      "dorothy_notify",
    ]);
  });
});
